spring:
  application:
    name: eureka-feign-client
server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: http://116.85.53.248:8761/eureka/

feign:
  hystrix:
    enabled: true

